[package]
name = "exchange"
version = "0.1.0"
edition = "2021"

[dependencies]
ordered-float = "5.0.0"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.2", features = ["full"] }
